import { createFileRoute, Link } from "@tanstack/react-router";
import { PageHero, SectionHeading, Card, Eyebrow } from "@/components/section";
import { FabricConsole } from "@/components/fabric-console";

export const Route = createFileRoute("/demo")({
  head: () => ({
    meta: [
      { title: "KHEPRA Trust OS — Live Public Demo" },
      {
        name: "description",
        content:
          "Invoke a read-only subset of the KHEPRA Trust Fabric without signing up. Every call is anchored on the shared evidence DAG and shown in the Console.",
      },
      { property: "og:title", content: "KHEPRA Trust OS — Live Public Demo" },
      {
        property: "og:description",
        content:
          "Read-only public demo of the KHEPRA Trust Fabric — SHA-256 anchored, replayable, no login required.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: DemoPage,
});

function DemoPage() {
  return (
    <>
      <PageHero
        eyebrow="Public Demo · No login"
        title={<>KHEPRA Trust OS — <span className="text-gradient">Live Public Demo</span></>}
        subtitle="Watch an AI agent build a verifiable proof-of-work history through the KHEPRA Trust OS Fabric — post-quantum identity, hash-chained evidence, dual-anchor determinism. Every record is built, hashed, and signed by the server evidence gateway; your browser only renders it. No login."
      />

      <section className="border-b border-border/60">
        <div className="container-x py-12">
          <FabricConsole />
          <p className="mt-4 text-center text-xs text-muted-foreground font-mono">
            The frontend is untrusted: it renders a signed Agent Evidence Object (AEO) from the <span className="text-foreground/80">/api/public/fabric</span> gateway, sourced from the sovereign MCP server (<span className="text-foreground/80">mcp.souhimbou.ai</span>). Browser renders — server validates, hashes, and signs.
          </p>
        </div>
      </section>

      <section className="border-b border-border/60">
        <div className="container-x py-16 space-y-16">
          <SectionHeading
            eyebrow="Interactive Demos"
            title="Live Incident DAGs"
            subtitle="Explore the actual interactive evidence chains generated by KHEPRA."
          />

          <div>
             <h3 className="text-xl font-bold mb-4">Target 1: DVWS (Control)</h3>
             <div className="rounded-xl overflow-hidden border border-border bg-background aspect-[21/9] shadow-2xl">
                <iframe src="/dvws-fair-dag.html" className="w-full h-full border-0" />
             </div>
          </div>

          <div>
             <h3 className="text-xl font-bold mb-4">Target 2: PentestGPT Incident</h3>
             <div className="rounded-xl overflow-hidden border border-border bg-background aspect-[21/9] shadow-2xl">
                <iframe src="/pentestgpt-fair-dag.html" className="w-full h-full border-0" />
             </div>
          </div>

          <div>
             <h3 className="text-xl font-bold mb-4">Target 3: HackGPT Incident</h3>
             <div className="rounded-xl overflow-hidden border border-border bg-background aspect-[21/9] shadow-2xl">
                <iframe src="/hackgpt-fair-dag.html" className="w-full h-full border-0" />
             </div>
          </div>
        </div>
      </section>

      <section className="border-b border-border/60">
        <div className="container-x py-16">
          <SectionHeading
            eyebrow="What just happened"
            title="Every call left a signed trail."
          />
          <div className="mt-8 grid md:grid-cols-3 gap-4 text-sm">
            {[
              ["1 · Invoke", "You hit /api/public/demo — a read-only, rate-limited public endpoint on the KHEPRA fabric."],
              ["2 · Anchor", "The response bytes were SHA-256 hashed and emitted as two AEO nodes (tool + attest) into the demo tenant's DAG."],
              ["3 · Replay", "Sign in and open /console/timeline — the public-demo session is pre-seeded with your calls, ready to replay and verify."],
            ].map(([t, d]) => (
              <Card key={t}>
                <div className="font-display text-base font-semibold">{t}</div>
                <p className="mt-2 text-muted-foreground leading-relaxed">{d}</p>
              </Card>
            ))}
          </div>
          <div className="mt-10 flex flex-wrap gap-3">
            <Link
              to="/auth"
              className="inline-flex items-center rounded-md bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground"
            >
              Open the Console →
            </Link>
            <Link
              to="/evidence-brief"
              className="inline-flex items-center rounded-md border border-primary text-primary px-5 py-2.5 text-sm font-medium"
            >
              View Forensic Chain of Custody
            </Link>
            <Link
              to="/protocol"
              className="inline-flex items-center rounded-md border border-border px-5 py-2.5 text-sm font-medium"
            >
              Read the protocol
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}

function ResultBlock({ r }: { r: DemoResult }) {
  const preview = JSON.stringify(r.result, null, 2);
  return (
    <div className="mt-4 space-y-3">
      <div className="flex flex-wrap gap-x-6 gap-y-1 text-xs">
        <span>
          verdict:{" "}
          <span className={r.verdict === "ok" ? "text-emerald-400" : "text-red-400"}>
            {r.verdict}
          </span>
        </span>
        <span className="text-muted-foreground">{r.durationMs}ms</span>
        <span className="font-mono text-muted-foreground truncate max-w-full">
          sha256:{r.responseSha256.slice(0, 24)}…
        </span>
        {r.evidence.sessionRef && (
          <span className="text-muted-foreground">
            session: <span className="font-mono">{r.evidence.sessionRef}</span>
          </span>
        )}
      </div>
      <pre className="max-h-72 overflow-auto rounded-md border border-border bg-background/60 p-3 text-xs font-mono leading-relaxed">
        {preview.length > 4000 ? preview.slice(0, 4000) + "\n…" : preview}
      </pre>
    </div>
  );
}