/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustNetworkRouteImport } from './routes/trust-network'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as AsafRouteImport } from './routes/asaf'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSouhimbouRouteImport } from './routes/products.souhimbou'
import { Route as ProductsAdinkhepraRouteImport } from './routes/products.adinkhepra'

const TrustNetworkRoute = TrustNetworkRouteImport.update({
  id: '/trust-network',
  path: '/trust-network',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AsafRoute = AsafRouteImport.update({
  id: '/asaf',
  path: '/asaf',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSouhimbouRoute = ProductsSouhimbouRouteImport.update({
  id: '/products/souhimbou',
  path: '/products/souhimbou',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAdinkhepraRoute = ProductsAdinkhepraRouteImport.update({
  id: '/products/adinkhepra',
  path: '/products/adinkhepra',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/asaf': typeof AsafRoute
  '/connectors': typeof ConnectorsRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust-network': typeof TrustNetworkRoute
  '/products/adinkhepra': typeof ProductsAdinkhepraRoute
  '/products/souhimbou': typeof ProductsSouhimbouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/asaf': typeof AsafRoute
  '/connectors': typeof ConnectorsRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust-network': typeof TrustNetworkRoute
  '/products/adinkhepra': typeof ProductsAdinkhepraRoute
  '/products/souhimbou': typeof ProductsSouhimbouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/asaf': typeof AsafRoute
  '/connectors': typeof ConnectorsRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust-network': typeof TrustNetworkRoute
  '/products/adinkhepra': typeof ProductsAdinkhepraRoute
  '/products/souhimbou': typeof ProductsSouhimbouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/asaf'
    | '/connectors'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/pricing'
    | '/protocol'
    | '/roadmap'
    | '/sitemap.xml'
    | '/trust-network'
    | '/products/adinkhepra'
    | '/products/souhimbou'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/asaf'
    | '/connectors'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/pricing'
    | '/protocol'
    | '/roadmap'
    | '/sitemap.xml'
    | '/trust-network'
    | '/products/adinkhepra'
    | '/products/souhimbou'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/asaf'
    | '/connectors'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/pricing'
    | '/protocol'
    | '/roadmap'
    | '/sitemap.xml'
    | '/trust-network'
    | '/products/adinkhepra'
    | '/products/souhimbou'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AsafRoute: typeof AsafRoute
  ConnectorsRoute: typeof ConnectorsRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  PricingRoute: typeof PricingRoute
  ProtocolRoute: typeof ProtocolRoute
  RoadmapRoute: typeof RoadmapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrustNetworkRoute: typeof TrustNetworkRoute
  ProductsAdinkhepraRoute: typeof ProductsAdinkhepraRoute
  ProductsSouhimbouRoute: typeof ProductsSouhimbouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-network': {
      id: '/trust-network'
      path: '/trust-network'
      fullPath: '/trust-network'
      preLoaderRoute: typeof TrustNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asaf': {
      id: '/asaf'
      path: '/asaf'
      fullPath: '/asaf'
      preLoaderRoute: typeof AsafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/souhimbou': {
      id: '/products/souhimbou'
      path: '/products/souhimbou'
      fullPath: '/products/souhimbou'
      preLoaderRoute: typeof ProductsSouhimbouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/adinkhepra': {
      id: '/products/adinkhepra'
      path: '/products/adinkhepra'
      fullPath: '/products/adinkhepra'
      preLoaderRoute: typeof ProductsAdinkhepraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AsafRoute: AsafRoute,
  ConnectorsRoute: ConnectorsRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  PricingRoute: PricingRoute,
  ProtocolRoute: ProtocolRoute,
  RoadmapRoute: RoadmapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrustNetworkRoute: TrustNetworkRoute,
  ProductsAdinkhepraRoute: ProductsAdinkhepraRoute,
  ProductsSouhimbouRoute: ProductsSouhimbouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
