/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustNetworkRouteImport } from './routes/trust-network'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AsafRouteImport } from './routes/asaf'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSouhimbouRouteImport } from './routes/products.souhimbou'
import { Route as ProductsAdinkhepraRouteImport } from './routes/products.adinkhepra'
import { Route as AuthenticatedConsoleRouteRouteImport } from './routes/_authenticated/console/route'
import { Route as ApiPublicAeoRouteImport } from './routes/api/public/aeo'
import { Route as AuthenticatedConsoleTimelineRouteImport } from './routes/_authenticated/console/timeline'
import { Route as AuthenticatedConsoleRulepacksRouteImport } from './routes/_authenticated/console/rulepacks'
import { Route as AuthenticatedConsoleFindingsRouteImport } from './routes/_authenticated/console/findings'
import { Route as AuthenticatedConsoleControlsRouteImport } from './routes/_authenticated/console/controls'
import { Route as AuthenticatedConsoleAgentsRouteImport } from './routes/_authenticated/console/agents'

const TrustNetworkRoute = TrustNetworkRouteImport.update({
  id: '/trust-network',
  path: '/trust-network',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AsafRoute = AsafRouteImport.update({
  id: '/asaf',
  path: '/asaf',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSouhimbouRoute = ProductsSouhimbouRouteImport.update({
  id: '/products/souhimbou',
  path: '/products/souhimbou',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAdinkhepraRoute = ProductsAdinkhepraRouteImport.update({
  id: '/products/adinkhepra',
  path: '/products/adinkhepra',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleRouteRoute =
  AuthenticatedConsoleRouteRouteImport.update({
    id: '/console',
    path: '/console',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAeoRoute = ApiPublicAeoRouteImport.update({
  id: '/api/public/aeo',
  path: '/api/public/aeo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleTimelineRoute =
  AuthenticatedConsoleTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedConsoleRouteRoute,
  } as any)
const AuthenticatedConsoleRulepacksRoute =
  AuthenticatedConsoleRulepacksRouteImport.update({
    id: '/rulepacks',
    path: '/rulepacks',
    getParentRoute: () => AuthenticatedConsoleRouteRoute,
  } as any)
const AuthenticatedConsoleFindingsRoute =
  AuthenticatedConsoleFindingsRouteImport.update({
    id: '/findings',
    path: '/findings',
    getParentRoute: () => AuthenticatedConsoleRouteRoute,
  } as any)
const AuthenticatedConsoleControlsRoute =
  AuthenticatedConsoleControlsRouteImport.update({
    id: '/controls',
    path: '/controls',
    getParentRoute: () => AuthenticatedConsoleRouteRoute,
  } as any)
const AuthenticatedConsoleAgentsRoute =
  AuthenticatedConsoleAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedConsoleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/asaf': typeof AsafRoute
  '/auth': typeof AuthRoute
  '/connectors': typeof ConnectorsRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust-network': typeof TrustNetworkRoute
  '/console': typeof AuthenticatedConsoleRouteRouteWithChildren
  '/products/adinkhepra': typeof ProductsAdinkhepraRoute
  '/products/souhimbou': typeof ProductsSouhimbouRoute
  '/console/agents': typeof AuthenticatedConsoleAgentsRoute
  '/console/controls': typeof AuthenticatedConsoleControlsRoute
  '/console/findings': typeof AuthenticatedConsoleFindingsRoute
  '/console/rulepacks': typeof AuthenticatedConsoleRulepacksRoute
  '/console/timeline': typeof AuthenticatedConsoleTimelineRoute
  '/api/public/aeo': typeof ApiPublicAeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/asaf': typeof AsafRoute
  '/auth': typeof AuthRoute
  '/connectors': typeof ConnectorsRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust-network': typeof TrustNetworkRoute
  '/console': typeof AuthenticatedConsoleRouteRouteWithChildren
  '/products/adinkhepra': typeof ProductsAdinkhepraRoute
  '/products/souhimbou': typeof ProductsSouhimbouRoute
  '/console/agents': typeof AuthenticatedConsoleAgentsRoute
  '/console/controls': typeof AuthenticatedConsoleControlsRoute
  '/console/findings': typeof AuthenticatedConsoleFindingsRoute
  '/console/rulepacks': typeof AuthenticatedConsoleRulepacksRoute
  '/console/timeline': typeof AuthenticatedConsoleTimelineRoute
  '/api/public/aeo': typeof ApiPublicAeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/asaf': typeof AsafRoute
  '/auth': typeof AuthRoute
  '/connectors': typeof ConnectorsRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/protocol': typeof ProtocolRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust-network': typeof TrustNetworkRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteRouteWithChildren
  '/products/adinkhepra': typeof ProductsAdinkhepraRoute
  '/products/souhimbou': typeof ProductsSouhimbouRoute
  '/_authenticated/console/agents': typeof AuthenticatedConsoleAgentsRoute
  '/_authenticated/console/controls': typeof AuthenticatedConsoleControlsRoute
  '/_authenticated/console/findings': typeof AuthenticatedConsoleFindingsRoute
  '/_authenticated/console/rulepacks': typeof AuthenticatedConsoleRulepacksRoute
  '/_authenticated/console/timeline': typeof AuthenticatedConsoleTimelineRoute
  '/api/public/aeo': typeof ApiPublicAeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/asaf'
    | '/auth'
    | '/connectors'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/pricing'
    | '/protocol'
    | '/roadmap'
    | '/sitemap.xml'
    | '/trust-network'
    | '/console'
    | '/products/adinkhepra'
    | '/products/souhimbou'
    | '/console/agents'
    | '/console/controls'
    | '/console/findings'
    | '/console/rulepacks'
    | '/console/timeline'
    | '/api/public/aeo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/asaf'
    | '/auth'
    | '/connectors'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/pricing'
    | '/protocol'
    | '/roadmap'
    | '/sitemap.xml'
    | '/trust-network'
    | '/console'
    | '/products/adinkhepra'
    | '/products/souhimbou'
    | '/console/agents'
    | '/console/controls'
    | '/console/findings'
    | '/console/rulepacks'
    | '/console/timeline'
    | '/api/public/aeo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/asaf'
    | '/auth'
    | '/connectors'
    | '/contact'
    | '/developers'
    | '/docs'
    | '/pricing'
    | '/protocol'
    | '/roadmap'
    | '/sitemap.xml'
    | '/trust-network'
    | '/_authenticated/console'
    | '/products/adinkhepra'
    | '/products/souhimbou'
    | '/_authenticated/console/agents'
    | '/_authenticated/console/controls'
    | '/_authenticated/console/findings'
    | '/_authenticated/console/rulepacks'
    | '/_authenticated/console/timeline'
    | '/api/public/aeo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AsafRoute: typeof AsafRoute
  AuthRoute: typeof AuthRoute
  ConnectorsRoute: typeof ConnectorsRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  DocsRoute: typeof DocsRoute
  PricingRoute: typeof PricingRoute
  ProtocolRoute: typeof ProtocolRoute
  RoadmapRoute: typeof RoadmapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrustNetworkRoute: typeof TrustNetworkRoute
  ProductsAdinkhepraRoute: typeof ProductsAdinkhepraRoute
  ProductsSouhimbouRoute: typeof ProductsSouhimbouRoute
  ApiPublicAeoRoute: typeof ApiPublicAeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-network': {
      id: '/trust-network'
      path: '/trust-network'
      fullPath: '/trust-network'
      preLoaderRoute: typeof TrustNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asaf': {
      id: '/asaf'
      path: '/asaf'
      fullPath: '/asaf'
      preLoaderRoute: typeof AsafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/souhimbou': {
      id: '/products/souhimbou'
      path: '/products/souhimbou'
      fullPath: '/products/souhimbou'
      preLoaderRoute: typeof ProductsSouhimbouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/adinkhepra': {
      id: '/products/adinkhepra'
      path: '/products/adinkhepra'
      fullPath: '/products/adinkhepra'
      preLoaderRoute: typeof ProductsAdinkhepraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/aeo': {
      id: '/api/public/aeo'
      path: '/api/public/aeo'
      fullPath: '/api/public/aeo'
      preLoaderRoute: typeof ApiPublicAeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console/timeline': {
      id: '/_authenticated/console/timeline'
      path: '/timeline'
      fullPath: '/console/timeline'
      preLoaderRoute: typeof AuthenticatedConsoleTimelineRouteImport
      parentRoute: typeof AuthenticatedConsoleRouteRoute
    }
    '/_authenticated/console/rulepacks': {
      id: '/_authenticated/console/rulepacks'
      path: '/rulepacks'
      fullPath: '/console/rulepacks'
      preLoaderRoute: typeof AuthenticatedConsoleRulepacksRouteImport
      parentRoute: typeof AuthenticatedConsoleRouteRoute
    }
    '/_authenticated/console/findings': {
      id: '/_authenticated/console/findings'
      path: '/findings'
      fullPath: '/console/findings'
      preLoaderRoute: typeof AuthenticatedConsoleFindingsRouteImport
      parentRoute: typeof AuthenticatedConsoleRouteRoute
    }
    '/_authenticated/console/controls': {
      id: '/_authenticated/console/controls'
      path: '/controls'
      fullPath: '/console/controls'
      preLoaderRoute: typeof AuthenticatedConsoleControlsRouteImport
      parentRoute: typeof AuthenticatedConsoleRouteRoute
    }
    '/_authenticated/console/agents': {
      id: '/_authenticated/console/agents'
      path: '/agents'
      fullPath: '/console/agents'
      preLoaderRoute: typeof AuthenticatedConsoleAgentsRouteImport
      parentRoute: typeof AuthenticatedConsoleRouteRoute
    }
  }
}

interface AuthenticatedConsoleRouteRouteChildren {
  AuthenticatedConsoleAgentsRoute: typeof AuthenticatedConsoleAgentsRoute
  AuthenticatedConsoleControlsRoute: typeof AuthenticatedConsoleControlsRoute
  AuthenticatedConsoleFindingsRoute: typeof AuthenticatedConsoleFindingsRoute
  AuthenticatedConsoleRulepacksRoute: typeof AuthenticatedConsoleRulepacksRoute
  AuthenticatedConsoleTimelineRoute: typeof AuthenticatedConsoleTimelineRoute
}

const AuthenticatedConsoleRouteRouteChildren: AuthenticatedConsoleRouteRouteChildren =
  {
    AuthenticatedConsoleAgentsRoute: AuthenticatedConsoleAgentsRoute,
    AuthenticatedConsoleControlsRoute: AuthenticatedConsoleControlsRoute,
    AuthenticatedConsoleFindingsRoute: AuthenticatedConsoleFindingsRoute,
    AuthenticatedConsoleRulepacksRoute: AuthenticatedConsoleRulepacksRoute,
    AuthenticatedConsoleTimelineRoute: AuthenticatedConsoleTimelineRoute,
  }

const AuthenticatedConsoleRouteRouteWithChildren =
  AuthenticatedConsoleRouteRoute._addFileChildren(
    AuthenticatedConsoleRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRouteRoute: typeof AuthenticatedConsoleRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRouteRoute: AuthenticatedConsoleRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AsafRoute: AsafRoute,
  AuthRoute: AuthRoute,
  ConnectorsRoute: ConnectorsRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  DocsRoute: DocsRoute,
  PricingRoute: PricingRoute,
  ProtocolRoute: ProtocolRoute,
  RoadmapRoute: RoadmapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrustNetworkRoute: TrustNetworkRoute,
  ProductsAdinkhepraRoute: ProductsAdinkhepraRoute,
  ProductsSouhimbouRoute: ProductsSouhimbouRoute,
  ApiPublicAeoRoute: ApiPublicAeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
